# ====== Usuall default
#seed = 10086
proj_name = "P4_DomNet_new"

# ======== Dataset and task related
batch_size = 128
num_class = 10
# ==== Model Structure ======
model_pretrain = "no"
model_structure = "sem"
L = 50
V = 4
# ======== Learning related
generations = 20
init_strategy = "mile"

	# ---- Interaction
int_lr = 1e-3
int_epochs = 20
	# ---- Distillation
dis_loss = "cesample"
dis_lr = 3e-4
dis_epochs = 2

run_name = "mile_dis2_L50V4_nopt_10cls_sgd"