# ====== Usuall default
#seed = 10086
proj_name = "P4_DomNet"

# ======== Dataset and task related
batch_size = 64

# ==== Model Structure ======
model_structure = "standard"
L = 20
V = 100
# ======== Learning related
generations = 1

	# ---- Interaction
int_lr = 1e-3
int_epochs = 200
	# ---- Distillation

run_name = "Res18_baseline_celeba"