# ====== Usuall default
#seed = 10086
proj_name = "P4_DomNet"

# ======== Dataset and task related
batch_size = 512

# ==== Model Structure ======
model_structure = "sem"
L = 20
V = 100
# ======== Learning related
generations = 10
init_strategy = "mile"

	# ---- Interaction
int_lr = 1e-3
int_epochs = 50
	# ---- Distillation
dis_lr = 1e-4
dis_epochs = 5

run_name = "mile_celeba"