# ====== Usuall default
#seed = 10086
proj_name = "P4_DomNet_new"

# ======== Dataset and task related
batch_size = 128
num_class = 20
# ==== Model Structure ======
model_pretrain = "yes"
model_structure = "standard"
L = 50
V = 4
# ======== Learning related
generations = 5
init_strategy = "mile"

	# ---- Interaction
int_lr = 3e-3
int_epochs = 100
	# ---- Distillation
dis_loss = "mse"
dis_lr = 3e-3
dis_epochs = 10

run_name = "only_int100dis10_L50V4_wpt_20cls_sgd"