# ====== Usuall default
#seed = 10086
proj_name = "P4_DomNet_directlabel"

# ======== Dataset and task related
batch_size = 128
num_class = 10
# ==== Model Structure ======
model_pretrain = "yes"
model_structure = "direct"
# ======== Learning related
generations = 10
init_strategy = "mile"

	# ---- Interaction
int_lr = 5e-3
int_epochs = 50
	# ---- Distillation
dis_loss = "cesample"
dis_lr = 3e-3
dis_epochs = 10

run_name = "mile_int50dis10_wpt_10cls_sgd"