# ====== Usuall default
#seed = 10086
proj_name = "P4_DomNet_new"

# ======== Dataset and task related
batch_size = 128

# ==== Model Structure ======
model_pretrain = "yes"
model_structure = "standard"
L = 60
V = 5
# ======== Learning related
generations = 1

	# ---- Interaction
int_lr = 1e-3
int_epochs = 200
	# ---- Distillation

run_name = "baseline_wpt"