# ====== Usuall default
#seed = 10086
proj_name = "P4_DomNet_new"

# ======== Dataset and task related
batch_size = 128
num_class = 10
# ==== Model Structure ======
model_pretrain = "yes"
model_structure = "sem"
L = 50
V = 4
# ======== Learning related
generations = 10
init_strategy = "nil"

	# ---- Interaction
int_lr = 1e-3
int_epochs = 50
	# ---- Distillation
dis_loss = "cesample"
dis_lr = 3e-4
dis_epochs = 20

run_name = "nil_L50V4_wpt_10cls"