# ====== Usuall default
#seed = 10086
proj_name = "P4_DomNet_new"

# ======== Dataset and task related
batch_size = 128
num_class = 5
# ==== Model Structure ======
model_pretrain = "yes"
model_structure = "sem"
L = 50
V = 4
# ======== Learning related
generations = 5
init_strategy = "mile"

	# ---- Interaction
int_lr = 3e-3
int_epochs = 40
	# ---- Distillation
dis_loss = "cesample"
dis_lr = 3e-3
dis_epochs = 10

run_name = "mile_int40dis10_L50V4_wpt_5cls_sgd"