# ====== Usuall default
#seed = 10086
proj_name = "P4_DomNet_new"

# ======== Dataset and task related
batch_size = 128

# ==== Model Structure ======
model_pretrain = "yes"
model_structure = "sem"
L = 60
V = 5
# ======== Learning related
generations = 10
init_strategy = "mile"

	# ---- Interaction
int_lr = 1e-3
int_epochs = 40
	# ---- Distillation
dis_loss = "cesample"
dis_lr = 3e-4
dis_epochs = 20

run_name = "mile_L60V5_wpt_adam"