# ====== Usuall default
#seed = 10086
proj_name = "P4_DomNet"

# ======== Dataset and task related
batch_size = 256

# ==== Model Structure ======
model_structure = "standard"
L = 20
V = 100
# ======== Learning related
generations = 1

	# ---- Interaction
int_lr = 1e-3
int_epochs = 500
	# ---- Distillation

run_name = "baseline_celeba"