# ====== Usuall default
#seed = 10086
proj_name = "P4_report"
drop_ratio = 0.5
batch_size = 128
dataset_name = "ogbg-molhiv"
bottle_type = "sem"

# ==== Model Structure ======
	# ----- Backbone and SEM
backbone_type = "gin"
emb_dim = 300
num_layer = 5
L = 100
V = 10
head_type = "linear"

# ==== NIL related ====== 
generations = 5
	# ---- Init student
init_strategy = "nil"
	# ---- Distillation
distill_data = "ogbg-molhiv"
distill_set = "train"
dis_steps = 100
dis_lr = 1e-3
dis_tau = 5
dis_optim = "adam"
dis_loss = "ce_sample"
	# ---- Interaction
int_epoch = 100
es_epochs = 5
int_lr = 1e-3
int_tau = 1
int_optim = "adamW"
#int_sched = true
	# ---- Generate teacher
copy_what = "best"
#save_model = true

run_name = "hiv_gin_semnil"