# ====== Usuall default
seed = 10086
proj_name = "P4_report"
drop_ratio = 0.5
batch_size = 64
dataset_name = "ogbg-molhiv"
bottle_type = "sem"

# ==== Model Structure ======
	# ----- Backbone and SEM
backbone_type = "gcn"
emb_dim = 300
num_layer = 5
L = 30
V = 10
head_type = "linear"

# ==== NIL related ====== 
generations = 10
	# ---- Init student
init_strategy = "mile"
	# ---- Distillation
distill_data = "ogbg-molhiv"
distill_set = "train"
dis_steps = 4000
dis_lr = 1e-3
dis_tau = 1
dis_optim = "adam"
dis_loss = "ce_sample"
	# ---- Interaction
int_epoch = 100
es_epochs = 5
int_lr = 1e-3
int_tau = 1
int_optim = "adam"
int_sched = true
	# ---- Generate teacher
copy_what = "best"

run_name = "hiv_gcn_semnil_addBN"