# ====== Usuall default
#seed = 10086
proj_name = "P4_report"
drop_ratio = 0.5
batch_size = 64
dataset_name = "ogbg-molhiv"
bottle_type = "std"

# ==== Model Structure ======
backbone_type = "gcn"
emb_dim = 300
num_layer = 5
generations = 1

	# ---- Interaction
int_epoch = 1000
es_epochs = 5
int_lr = 1e-3
int_optim = "adam"
int_sched = true
save_model = true

run_name = "hiv_gcn_baseline_tab1"