# ====== Usuall default
#seed = 10086
proj_name = "P4_report"
drop_ratio = 0.5
batch_size = 64
dataset_name = "ogbg-molhiv"
dataset_hardsplit = "hard_0p5"
bottle_type = "sem"
# ==== Model Structure ======
backbone_type = "gcn"
head_type = "linear"
emb_dim = 300
num_layer = 5
generations = 1
L = 45
V = 45

	# ---- Interaction
int_epoch = 500
int_lr = 1e-3
int_optim = "adamw"
int_sched = true
#save_model = true

run_name = "hiv_gcn_sem_hard_0p5"