# ====== Usuall default
#seed = 10086
proj_name = "P4_report"
drop_ratio = 0
batch_size = 64
dataset_name = "ogbg-molhiv"
bottle_type = "sem"

# ==== Model Structure ======
backbone_type = "gcn"
head_type = "linar"
emb_dim = 300
num_layer = 5
generations = 1
L = 100
V = 20

	# ---- Interaction
int_epoch = 1000
int_lr = 1e-3
int_optim = "adamW"
int_sched = true
save_model = true

run_name = "hiv_gcn_sem_tab1"