# ====== Usuall default
proj_name = "P4_report"
drop_ratio = 0.5
batch_size = 32
dataset_name = "ogbg-molhiv"
bottle_type = "sem"

# ==== Model Structure ======
	# ----- Backbone and SEM
backbone_type = "gcn"
emb_dim = 300
num_layer = 5
L = 30
V = 10
head_type = "linear"

# ==== NIL related ====== 
generations = 15
	# ---- Init student
init_strategy = "mile"
	# ---- Distillation
dis_steps = 2000
dis_lr = 1e-4
dis_tau = 1
dis_optim = "adam"
dis_loss = "ce_sample"
	# ---- Interaction
int_tau = 1
int_epoch = 20
es_epochs = 5
int_lr = 1e-3
int_optim = "adam"
int_sched = true
	# ---- Generate teacher
copy_what = "last"

run_name = "hiv_gcn_semmile_linear"