# ====== Usuall default
#seed = 10086
proj_name = "P4_report"
drop_ratio = 0.5
batch_size = 64
dataset_name = "ogbg-molhiv"
bottle_type = "sem"

# ==== Model Structure ======
	# ----- Backbone and SEM
backbone_type = "gin"
emb_dim = 300
num_layer = 3
L = 43
V = 31
head_type = "linear"

# ==== NIL related ====== 
generations = 8
	# ---- Init student
init_strategy = "mile"
	# ---- Distillation
distill_data = "ogbg-molhiv"
distill_set = "train"
dis_steps = 5000
dis_lr = 1e-3
dis_tau = 0.96
dis_optim = "adam"
dis_loss = "ce_sample"
	# ---- Interaction
int_epoch = 100
es_epochs = 3
int_lr = 1e-3
int_tau = 2.28
int_optim = "adamW"
int_sched = false
	# ---- Generate teacher
copy_what = "best"
#save_model = true

run_name = "hiv_gin_semnil"