# ====== Usuall default
drop_ratio = 0
batch_size = 64
dataset_name = "ogbg-molhiv"
bottle_type = "sem"

# ==== Model Structure ======
backbone_type = "gcn"
head_type = "mlp"
emb_dim = 300
num_layer = 5
generations = 1

	# ---- Interaction
int_epoch = 100
es_epochs = 5
int_lr = 1e-1
int_optim = "sgd"
int_sched = true

run_name = "hiv_gcn_sem_sgd_biglr"