# ====== Usuall default
#seed = 10086
proj_name = "P4_report"
drop_ratio = 0.5
batch_size = 256
dataset_name = "ogbg-molpcba"
dataset_hardsplit = "hard_0p9"
bottle_type = "sem"

# ==== Model Structure ======
	# ----- Backbone and SEM
backbone_type = "gin"
emb_dim = 300
num_layer = 5
L = 100
V = 20
head_type = "linear"

# ==== NIL related ====== 
generations = 15
	# ---- Init student
init_strategy = "mile"
	# ---- Distillation
distill_data = "ogbg-molpcba"
distill_set = "train"
dis_steps = 1000
dis_lr = 1e-3
dis_tau = 1
dis_optim = "adam"
dis_loss = "ce_sample"
	# ---- Interaction
int_epoch = 50
es_epochs = 5
int_lr = 1e-3
int_tau = 1
int_optim = "adam"
int_sched = true
	# ---- Generate teacher
copy_what = "best"
#save_model = true

run_name = "pcba_gin_semmile_hard0p9_last"