# ====== Usuall default
#seed = 1034
proj_name = "P4_report"
drop_ratio = 0.5
batch_size = 64
dataset_name = "ogbg-molpcba"
dataset_hardsplit = "hard_0p5"
bottle_type = "sem"

# ==== Model Structure ======
	# ----- Backbone and SEM
backbone_type = "gin"
emb_dim = 300
num_layer = 3
L = 45
V = 45
head_type = "linear"

# ==== NIL related ====== 
generations = 10
	# ---- Init student
init_strategy = "mile"
	# ---- Distillation
distill_data = "ogbg-molpcba"
distill_set = "train"
dis_steps = 10000
dis_lr = 1e-3
dis_tau = 1
dis_optim = "adamw"
dis_loss = "ce_sample"
	# ---- Interaction
int_epoch = 50
es_epochs = 3
int_lr = 1e-3
int_tau = 2
int_optim = "adamw"
int_sched = true
	# ---- Generate teacher
copy_what = "best"
#save_model = true

run_name = "pcba_gin_semmile_hard0p5"