# ====== Usuall default
#seed = 10086
proj_name = "P4_report"
drop_ratio = 0.5
batch_size = 256
dataset_name = "ogbg-molpcba"
dataset_hardsplit = "hard_0p9"
bottle_type = "sem_base"

# ==== Model Structure ======
backbone_type = "gin"
head_type = "linear"
emb_dim = 300
num_layer = 5
generations = 1
L = 100
V = 20


	# ---- Interaction
int_epoch = 1000
int_lr = 1e-3
int_optim = "adam"
int_sched = true
save_model = false

run_name = "pcba_gin_baselineplus_hard0p9"