# ====== Usuall default
seed = 10086
proj_name = "P4_report"
drop_ratio = 0
batch_size = 256
dataset_name = "pcqm"
bottle_type = "sem"

# ==== Model Structure ======
	# ----- Backbone and SEM
backbone_type = "gcn"
emb_dim = 600
num_layer = 5
L = 40
V = 20
head_type = "mlp"

# ==== NIL related ====== 
generations = 10
	# ---- Init student
init_strategy = "nil"
	# ---- Distillation
distill_data = "pcqm"
distill_set = "train"
dis_steps = 40000
dis_lr = 3e-3
dis_tau = 0.2
dis_optim = "adamW"
dis_loss = "ce_sample"
	# ---- Interaction
int_epoch = 20
es_epochs = 5
int_lr = 1e-3
int_tau = 1
int_optim = "adamW"
int_sched = true
	# ---- Generate teacher
copy_what = "last"

run_name = "pcqm_gcn_semnil"