# ====== Usuall default
seed = 10086
proj_name = "P4_report"
drop_ratio = 0
batch_size = 256
dataset_name = "pcqm"
bottle_type = "sem"

# ==== Model Structure ======
backbone_type = "gcn"
head_type = "mlp"
emb_dim = 600
num_layer = 5
generations = 1

	# ---- Interaction
int_epoch = 200
int_lr = 1e-3
int_optim = "adamW"
int_sched = true
save_model = true

run_name = "pcqm_gcn_sem_save"