# ====== Usuall default
seed = 10086
proj_name = "P4_report"
drop_ratio = 0
batch_size = 512
dataset_name = "pcqm"
bottle_type = "sem"

# ==== Model Structure ======
	# ----- Backbone and SEM
backbone_type = "gin"
emb_dim = 300
num_layer = 5
L = 30
V = 10
head_type = "linear"

# ==== NIL related ====== 
generations = 5
	# ---- Init student
init_strategy = "mile"
	# ---- Distillation
distill_data = "pcqm"
distill_set = "train"
dis_steps = 20000
dis_lr = 3e-3
dis_optim = "adamW"
dis_loss = "ce_sample"
	# ---- Interaction
int_epoch = 20
es_epochs = 5
int_lr = 1e-3
int_tau = 1
int_optim = "adamW"
int_sched = true
	# ---- Generate teacher
copy_what = "best"
save_model = true

run_name = "pcqm_gin_semnil_L30V10"