# ====== Usuall default
seed = 10086
proj_name = "P4_report"
drop_ratio = 0.5
batch_size = 64
dataset_name = "ogbg-molpcba"
bottle_type = "std"

# ==== Model Structure ======
backbone_type = "gcn"
emb_dim = 300
num_layer = 5
generations = 1

	# ---- Interaction
int_epoch = 500
es_epochs = 5
int_lr = 1e-3
int_optim = "adamW"
int_sched = true
save_model = true

#----- Here is the difference
dataset_ratio = 0.1

run_name = "pcba_gcn_baseline_subset"