# ====== Usuall default
#seed = 10086
proj_name = "P4_report"
drop_ratio = 0.5
batch_size = 64
dataset_name = "ogbg-molpcba"
bottle_type = "sem"

# ==== Model Structure ======
backbone_type = "gcn"
head_type = "mlp"
emb_dim = 300
num_layer = 5
generations = 1
L=30
V=10

	# ---- Interaction
int_epoch = 100
es_epochs = 5
int_lr = 1e-3
int_optim = "adamW"
int_sched = true
save_model = true

#----- Here is the difference
dataset_ratio = 1
dataset_forcetask = 1

run_name = "pcba_gcn_sem_subtask"