# ====== Usuall default
seed = 10086
proj_name = "P4_toy"

# ======== Dataset and task related
sup_ratio = 0.2
batch_size = 20
data_per_g = 1

# ==== Model Structure ======
model_structure = "sem"
L=4
V=10

# ======== Learning related
generations = 1

	# ---- Interaction
int_lr = 1e-3
int_epochs = 2000
	# ---- Distillation

run_name = "Alpha02_baseline_sem"