# ====== Usuall default
#seed = 10086     #---- Not use this when sweeping
proj_name = "P4_toy"
#dataset_name = "mpi3d"
dataset_name = "dsprites"    #dsprites needs different hypers

# ======== Dataset and task related
#sup_ratio = 0.2   #---- Not use this when sweeping
batch_size = 128
#data_per_g = 5
num_class = 1

dis_dataset = "train"
# ==== Model Structure ======
model_structure = "sem"
L=4
V=10

# ======== Learning related
init_strategy = "mile"
generations = 10
bob_adapt_ep = 2

	# ---- Interaction
int_lr = 1e-3
int_epochs = 500
	# ---- Distillation
dis_lr = 1e-3
dis_epochs = 50
dis_loss = "cesample"

copy_what = "best"

run_name_seed = "dsprites_milesem_k1"