# ====== Usuall default
seed = 10086
proj_name = "P4_toy"

# ======== Dataset and task related
sup_ratio = 0.2
batch_size = 128
data_per_g = 1
num_class = 1

# ==== Model Structure ======
model_structure = "sem"
L=4
V=10

# ======== Learning related
init_strategy = "mile"
generations = 10

	# ---- Interaction
int_lr = 1e-3
int_epochs = 200
	# ---- Distillation
dis_lr = 1e-3
dis_epochs = 50
dis_loss = "mse"

copy_what = "best"

run_name = "nilonly_sup0p2_k1"