# ====== Usuall default
#seed = 10086
proj_name = "P4_toy"
dataset_name = "dsprites"

# ======== Dataset and task related
#sup_ratio = 0.2 #---- Not use this when sweeping
batch_size = 128
data_per_g = 1
num_class = 1

# ==== Model Structure ======
model_structure = "standard"

# ======== Learning related
generations = 1

	# ---- Interaction
int_lr = 1e-3
int_epochs = 2000
	# ---- Distillation

run_name_seed = "dsprites_base_k1"