# ====== Usuall default
seed = 10086
proj_name = "P4_toy"

# ======== Dataset and task related
sup_ratio = 0.1
batch_size = 50
data_per_g = 1
num_class = 1
dis_dataset = train
# ==== Model Structure ======
model_structure = "sem"
L=4
V=10

# ======== Learning related
init_strategy = "mile"
generations = 10
bob_adapt_ep = 0

	# ---- Interaction
int_lr = 1e-3
int_epochs = 200
	# ---- Distillation
dis_lr = 1e-3
dis_epochs = 20
dis_loss = "cesample"

copy_what = "best"

run_name = "milesem_sup0p1_k1"